### ISSUE TITLE
NullPointerException when rotate screen

### ISSUE THREAD

**Issue by maddog05** [merhold/extensible-page-indicator#1]
I have this problem when the screen rotate:

> FATAL EXCEPTION: main
>                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.view.ViewPager.removeOnPageChangeListener(android.support.v4.view.ViewPager$OnPageChangeListener)' on a null object reference
>                                                                                at com.merhold.extensiblepageindicator.ExtensiblePageIndicator.onDetachedFromWindow(ExtensiblePageIndicator.java:217)
>                                                                                at android.view.View.dispatchDetachedFromWindow(View.java:13578)
>                                                                                at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2836)
>                                                                                at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2836)
>                                                                                at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2836)
>                                                                                at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2836)
>                                                                                at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2836)
>                                                                                at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2836)
>                                                                                at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3008)
>                                                                                at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5566)
>                                                                                at android.view.ViewRootImpl.die(ViewRootImpl.java:5543)
>                                                                                at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:369)
>                                                                                at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:324)
>                                                                                at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
>                                                                                at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3827)
>                                                                                at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4009)
>                                                                                at android.app.ActivityThread.access$900(ActivityThread.java:155)
>                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
>                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                at android.os.Looper.loop(Looper.java:135)
>                                                                                at android.app.ActivityThread.main(ActivityThread.java:5343)
>                                                                                at java.lang.reflect.Method.invoke(Native Method)
>                                                                                at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
>                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by maddog05** [comment]
More specific, this error appear when my ViewPager doesn't set a PagerAdapter
